import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({ baseDirectory: import.meta.dirname });

export default [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    // next-env.d.ts is a Next.js-generated file (gitignored; regenerated by
    // `next dev`/`next build`; its own header says "should not be edited") —
    // lint-ignored like ink-icons.generated.ts, not "fixed".
    // .claude/worktrees/ holds throwaway agent worktrees whose own .next/ and
    // node_modules/ escape the root-relative ignores above — never lint them.
    // .next-dev/ is the dev server's dist dir (see next.config.mjs): gitignored
    // like .next/, but eslint reads this list rather than .gitignore, so a
    // running `pnpm dev` would otherwise fail `pnpm lint` on bundled vendor code.
    ignores: [".next/**", ".next-dev/**", "node_modules/**", ".claude/worktrees/**", "components/ink-icons.generated.ts", "next-env.d.ts", "plugins/dx-harness/checks/fixtures/**"],
  },
];
