import Link from "next/link";
import {
  noticeSummary,
  thirdPartyNotices,
} from "@/lib/third-party-notices.generated";

/* Third-party notices. MIT, ISC and BSD grant redistribution on the condition
   that their copyright and permission notices appear in the copies you ship, so
   a link to someone else's repository does not discharge it — the text has to be
   served from here. Generated by scripts/generate-notices.mjs from the installed
   tree, never hand-kept, because a list maintained by hand goes stale silently
   and a stale notice file is worse than an honest short one.

   Each package also links to its upstream repository. That link is provenance,
   not discharge: it lets a reader compare a notice against its source, while the
   text above it is what actually satisfies the condition. Worth being precise
   about why the two are not interchangeable — the notice owed is the one shipped
   by the version pinned in the lockfile, and that text does not change when
   upstream relicenses later work, so serving it here is both the compliant and
   the stable answer. `pnpm check:notices` runs in prebuild and fails the build if
   these files drift from the installed tree.

   A server component on purpose: the notice data is ~200KB and belongs in the
   prerendered HTML, not in a client bundle a reader has to download to see a
   page of static text. */

export const metadata = {
  title: "Third-party notices",
  description:
    "The open-source licenses this site is built on, reproduced in full.",
};

export default function LegalPage() {
  return (
    <article className="px-6 py-16 sm:px-10 sm:py-20">
      <div className="mx-auto max-w-[720px]">
        <h1 className="font-display text-3xl font-semibold tracking-tight text-balance">
          Third-party notices
        </h1>

        <p className="mt-6 text-base leading-relaxed text-muted-foreground">
          This project is licensed under GPL-3.0 — see{" "}
          <a
            href="https://github.com/transformteamsg/dx-harness/blob/main/LICENSE"
            className="text-foreground underline underline-offset-4"
          >
            LICENSE
          </a>
          . It is built on open-source packages whose licenses let us
          redistribute them on one condition: that their notices travel with
          every copy we ship. Those notices are reproduced below in full.
        </p>

        <h2 className="mt-12 font-display text-xl font-semibold tracking-tight">
          Lucide icon artwork
        </h2>
        <p className="mt-4 text-base leading-relaxed text-muted-foreground">
          The hand-drawn icons on this site are derived from{" "}
          <a
            href="https://lucide.dev"
            className="text-foreground underline underline-offset-4"
          >
            Lucide
          </a>{" "}
          (ISC), re-rendered through rough.js into the brand&apos;s ink style.
          Derivative artwork carries the same notice as the original, so the
          Lucide license below covers the icons as well as the package. Anyone
          redistributing these icons needs to carry it too — see{" "}
          <Link
            href="/foundations/iconography"
            className="text-foreground underline underline-offset-4"
          >
            Iconography
          </Link>
          .
        </p>

        <h2 className="mt-12 font-display text-xl font-semibold tracking-tight">
          Packages
        </h2>
        <p className="mt-4 text-base leading-relaxed text-muted-foreground">
          {noticeSummary.packageCount} packages across{" "}
          {noticeSummary.licenseCount} licenses, grouped by the exact notice
          text they ship. Read from the installed dependency tree, so this list
          describes what the site is actually built from.
        </p>

        <div className="mt-10 space-y-12">
          {thirdPartyNotices.map((group) => (
            <section key={`${group.license}-${group.packages[0].name}`}>
              <h3 className="font-display text-base font-semibold tracking-tight">
                {group.license}
              </h3>
              {/* The package name links to its upstream source where one is
                  declared, and renders as plain text where none is — rather than
                  a link to a guessed URL. */}
              <ul className="mt-3 flex flex-wrap gap-x-3 gap-y-1 text-xs text-muted-foreground">
                {group.packages.map((pkg) => (
                  <li key={pkg.name}>
                    {pkg.source ? (
                      <a
                        href={pkg.source}
                        className="underline underline-offset-2 hover:text-foreground"
                      >
                        {pkg.name}
                        {pkg.version ? ` ${pkg.version}` : ""}
                      </a>
                    ) : (
                      <>
                        {pkg.name}
                        {pkg.version ? ` ${pkg.version}` : ""}
                      </>
                    )}
                  </li>
                ))}
              </ul>
              {group.text ? (
                <pre className="mt-4 overflow-x-auto rounded-lg border border-border bg-muted p-4 text-xs leading-[1.6] whitespace-pre-wrap text-foreground">
                  {group.text}
                </pre>
              ) : (
                <p className="mt-4 text-xs text-muted-foreground">
                  This package declares {group.license} but ships no license
                  file of its own.
                </p>
              )}
            </section>
          ))}
        </div>
      </div>
    </article>
  );
}
